---
name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
      - test/setup-#5 # TODO: remove after testing

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["nightly", "stable"]

    steps:
      - uses: actions/checkout@v5
        with: # TODO: remove after testing
          ref: test/setup-#5
      - name: Run tests
        uses: lumen-oss/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
